In [5]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def new_perc(w1, w2, b):
    return sigmoid(0.4*(w1)+0.6*(w2)+b)
# Try out
print(new_perc(2, 6, -2))
print(new_perc(3, 5, -2.2))
print(new_perc(5, 4, -3))

0.9168273035060777
0.8807970779778823
0.8021838885585818


In [7]:
y=np.array(0.5)
print(y)

0.5


In [24]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))

print(weights_input_to_hidden)
#print(weights_hidden_to_output)
print(X)

[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]
[ 0.49671415 -0.1382643   0.64768854  1.52302986]


In [26]:
# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]
